name: "Check Builds"
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - '.gitattributes'
    - '.gitmodules'
    - 'skaffold.yaml'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - '.gitattributes'
    - '.gitmodules'
    - 'skaffold.yaml'
jobs:
  build-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - uses: cachix/install-nix-action@v10
    - run: nix-build -A shell

  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: |
        nix-build -A staticSiteContent \
        --arg crossSystem '{ config = "x86_64-unknown-linux-musl"; }' \
        --argstr system x86_64-linux
  build-container:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: |
        nix-build -A siteServerContainer \
        --arg crossSystem '{ config = "x86_64-unknown-linux-musl"; }' \
        --argstr system x86_64-linux
